name: Terraform Destroy

on: [workflow_dispatch]

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  enable-https:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

      # Setup terraform env.
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.0
      with:
        terraform_version: 1.1.7

    - name: Terraform Init
      working-directory: terraform
      id: init
      run: terraform init -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" -backend-config="prefix=terraform/state-${{ secrets.VM_NAME_PREFIX }}"

    - name: Terraform Destroy
      working-directory: terraform
      id: destroy
      run: terraform destroy -force