name: Terraform Create/Update - Deploy/Update Full Environment

on: [workflow_dispatch]

env:
  TF_VAR_GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
  TF_VAR_VM_ZONES: ${{ secrets.VM_ZONES }}
  TF_VAR_VM_NAME_PREFIX: ${{ secrets.VM_NAME_PREFIX }}
  TF_VAR_ORCHESTRATOR_SERVICE_DIRECTORY_PATH: "/../orchestrator-service/services/ServicePixelStreamingOrchestrator/"
  TF_VAR_ORCHESTRATOR_VM_INSTALL_SH_FILE_PATH: "/../install_prerequisites-gc-orchestrator-vm.sh"
  TF_VAR_GPU_VM_INSTALL_SH_FILE_PATH: "/../install_prerequisites-gc-gpu-vm.sh"
  TF_VAR_DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  TF_VAR_ORCHESTRATOR_CONTAINER_NAME: ${{ secrets.ORCHESTRATOR_CONTAINER_NAME }}
  TF_VAR_PIXEL_STREAMING_UNREAL_CONTAINER_IMAGE_NAME: ${{ secrets.PIXEL_STREAMING_UNREAL_CONTAINER_IMAGE_NAME }}
  TF_VAR_MAX_USER_SESSION_PER_INSTANCE: ${{ secrets.MAX_USER_SESSION_PER_INSTANCE }}
  TF_VAR_GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  terraform-create:
    name: Terraform Create
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        export_default_credentials: true

    # Setup dotnet env. (Used in Terraform for build)
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'

    # Setup terraform env.
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.0
      with:
        terraform_version: 1.1.7

    - name: Terraform Init
      working-directory: terraform
      id: init
      run: terraform init -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" -backend-config="prefix=terraform/state-${{ secrets.VM_NAME_PREFIX }}"

    - name: Terraform Validate
      working-directory: terraform
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      working-directory: terraform
      id: plan
      run: terraform plan -input=false

    - name: Terraform Apply
      working-directory: terraform
      id: apply
      run: terraform apply -auto-approve -input=false